"""Add amenity and service_amenities tables

Revision ID: 872a0eaffe0e
Revises: f2c4b8a1d9e7
Create Date: 2026-02-16 03:38:45.130772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '872a0eaffe0e'
down_revision = 'f2c4b8a1d9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_es', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_pt', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_amenities',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['camping_services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'amenity_id')
    )
    with op.batch_alter_table('camping_services', schema=None) as batch_op:
        batch_op.drop_column('amenities_csv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camping_services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities_csv', mysql.TEXT(), nullable=True))

    op.drop_table('service_amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
