"""Initial camping migration

Revision ID: 90b0dee3a10f
Revises: 
Create Date: 2026-02-15 21:55:44.474057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b0dee3a10f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('camping_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('service_type', sa.String(length=30), nullable=False),
    sa.Column('name_es', sa.String(length=160), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=False),
    sa.Column('name_pt', sa.String(length=160), nullable=False),
    sa.Column('description_es', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_pt', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('available_units', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_promo', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('amenities_csv', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camping_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camping_services_service_type'), ['service_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_camping_services_slug'), ['slug'], unique=True)

    op.create_table('citizen_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citizen_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citizen_users_supabase_uid'), ['supabase_uid'], unique=True)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hero_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_object_name'), ['object_name'], unique=True)

    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements_json', sa.Text(), nullable=True),
    sa.Column('cost', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('current_bookings', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=140), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirmation_token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['camping_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pre_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_reservations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_pre_reservations_confirmation_token'), ['confirmation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_pre_reservations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_reservations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_reservations_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_reservations_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_reservations_status'), ['status'], unique=False)

    op.create_table('procedure_localities',
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'locality_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['citizen_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['camping_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_images_service_id'), ['service_id'], unique=False)

    op.create_table('service_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment_es', sa.Text(), nullable=False),
    sa.Column('comment_en', sa.Text(), nullable=False),
    sa.Column('comment_pt', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['camping_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_reviews_service_id'), ['service_id'], unique=False)

    op.create_table('two_factor_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confirmation_token', sa.String(length=100), nullable=True),
    sa.Column('cancellation_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['appointment_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancellation_token'),
    sa.UniqueConstraint('confirmation_token')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_ci'), ['ci'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_code'), ['code'], unique=True)

    op.create_table('sent_emails_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('area_notified', sa.String(length=100), nullable=True),
    sa.Column('sent_by_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['sent_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_emails_log')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_code'))
        batch_op.drop_index(batch_op.f('ix_reservations_ci'))

    op.drop_table('reservations')
    op.drop_table('two_factor_codes')
    with op.batch_alter_table('service_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_reviews_service_id'))

    op.drop_table('service_reviews')
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_images_service_id'))

    op.drop_table('service_images')
    op.drop_table('reports')
    op.drop_table('procedure_localities')
    with op.batch_alter_table('pre_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_pre_reservations_service_id'))
        batch_op.drop_index(batch_op.f('ix_pre_reservations_expires_at'))
        batch_op.drop_index(batch_op.f('ix_pre_reservations_email'))
        batch_op.drop_index(batch_op.f('ix_pre_reservations_created_at'))
        batch_op.drop_index(batch_op.f('ix_pre_reservations_confirmation_token'))
        batch_op.drop_index(batch_op.f('ix_pre_reservations_code'))

    op.drop_table('pre_reservations')
    op.drop_table('appointment_slots')
    op.drop_table('activity_logs')
    op.drop_table('suggestions')
    op.drop_table('procedures')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_object_name'))

    op.drop_table('media_assets')
    op.drop_table('localities')
    op.drop_table('hero_images')
    op.drop_table('contacts')
    with op.batch_alter_table('citizen_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citizen_users_supabase_uid'))

    op.drop_table('citizen_users')
    with op.batch_alter_table('camping_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camping_services_slug'))
        batch_op.drop_index(batch_op.f('ix_camping_services_service_type'))

    op.drop_table('camping_services')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
